spring.datasource.url=jdbc:postgresql://ep-mute-salad-aq3aw30m.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_p7gzXmJcA6Nf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true